const EXT_CONFIG = {
  BUBBLE_TEXT_ENDPOINT: "https://bubbletext.io",
  MAX_TEXTS_COUNT: 7,
  MAX_BUBBLES_COUNT: 5,
  MAX_ANIMATIONS_COUNT: 3,
  MAIN_COLOR: "#d91b5b",
  ADDITIONAL_COLOR: "#262261",
  SELECTED_COLOR: "#a5ce00",
  THEME: false,
  BUBBLE_POPIN_ANIM_DURATION: 0.4,
  WIDGET_DURATION: 15000,
  WIDGET_DELAY_BEFORE_NEXT_BUBBLE: 1000,
  PREVIEW_WIDGET_DURATION: 4000,
  PREVIEW_WIDGET_DELAY_BEFORE_NEXT_BUBBLE: 750,
  DARK_THEME: {
    BACKGROUND: "#19171c"
  },
  LIGHT_THEME: {
    BACKGROUND: "white"
  },
  NOTIFICATION_SHOW_TIME: 15000
};

export default EXT_CONFIG;
