export const RECENT_MATCHES = 'RECENT_MATCHES';
export const MATCH_DETAILS = 'MATCH_DETAILS';
export const STREAMER_CONFIG = 'STREAMER_CONFIG';
export const SET_STREAMER_CONFIG = 'SET_STREAMER_CONFIG';